name: Issues Similarity Analysis

on:
  issues:
    types: [opened, edited]

jobs:
  similarity-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: analysis
        uses: actions-cool/issues-similarity-analysis@v1
        with:
          show-footer: false
          comment-title: '### Similar issues'
          comment-body: '${index}. ${similarity} #${number}'
          show-mentioned: true
          filter-threshold: 0.6
          since-days: 730
